[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "make-fastapi-app"
description = "Creates a FastAPI app that is ready to be deployed on Docker hosts like DigitalOcean / Render.com"
requires-python = ">=3.7"
keywords = ["template-python-cmd"]
license = { text = "BSD 3-Clause License" }
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "pytest",
]
readme = "README.md"
maintainers = [
    {name = "Zachary Vorhies"}
]
# Change this with the version number bump.
# Also make the change in zcmds/version.py
version = "1.0.5"

[tool.pylint."MESSAGES CONTROL"]
good-names = [
    "c",
    "i",
    "ok",
    "id",
    "e",
    "f"
]

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true

[project.optional-dependencies]
dev = [
    "black",
    "isort", 
    "flake8",
    "mypy",
    "pylint",
    "pytest",
    "tox"
]

[project.scripts]
make-fastapi-app = "createfastapiapp.createapp:create_python_app"
